- src/App.php
- src/Config.php
add phar protocol support for Config load function
> add phar protocol support

- src/App.php
- src/Route.php
> fixed: is_callable support PHP8

- src/App.php
Compatible with the 'realpath' function in the phar file.
> Phar support.

- src/Route.php
> resource bug

- src/support/Plugin.php
> plugin Install/uninstall

- src/support/bootstrap/LaravelDb.php
Add yet another paginator resolvers
> Add Paginator resolvers

- src/App.php
> fix: admin url 404 问题

- src/Container.php
config/container.php
```php
return (new Webman\Container)
->addDefinitions(config('dependence', []));
```
config/dependence.php
```php
use Psr\Container\ContainerInterface;
return [
'abc' => function (ContainerInterface $container) {
return 'XYZ'
}
];
```
```php
use support\Container;
$is = Container::has('abc'); // true
$value = Container::get('abc'); // XYZ
```
> Container 支持依赖注入

- src/support/Redis.php
Add static prompt to eval method
> Add static prompt to eval method

- src/support/Plugin.php
支持composer的`update`事件方法，如果插件未定义此方法，仍然走`install`方法。
`install`方法传入一个参数`true|false`判断是新安装还是升级。
> Support plugin update event

- src/App.php
优化了guessControllerAction()，getController()等相关代码，避免遍历目录，直接判断文字是否存在。不过目录名需要一定规范，比如url为/some-other/get-some-data，则some-other对应目录名应为some-other，而不是someother，SomeOther等 。
> 改进url解析需要多次遍历目录文件的问题，大幅提升性能。

- src/App.php
让/userlogin/testuser能对应app\controller\UserLogin::testUser，上一版url需为/user-login/test-user或/user-login/testuser
> 对url对应规则做兼容处理

- src/Middleware.php
> feat:增加全局中间件调用

- src/support/Translation.php
This update enhances the Translation class to support loading translation files from multiple directories. Previously, the class was limited to a single translation path, but now it can handle an array of paths, allowing for a more flexible and organized structure for managing translations.
> Multi-Directory Support in Translation Class

- src/App.php
新增可配置超全局异常处理类逻辑,用以优化当应用插件未配置异常处理类时使用超全局异常处理类逻辑
当主应用设置@超全局异常处理类时并且插件模块没有设置异常处理类时使用超全局异常处理类
```
return [
'@' => core\exception\ApiHandler::class,
];
```
> feat:新增可配置超全局异常处理类逻辑,用以优化当应用插件未配置异常处理类时使用超全局异常处理类逻辑

- composer.json
- src/Annotation/Middleware.php
- src/App.php
- src/Middleware.php
- 修改 App.php 中的中间件加载逻辑，以支持新的方式
- 更新 Middleware.php 中的 getMiddleware 方法，增加对属性和方法属性的支持
- 新增对控制器类和方法的反射处理，以获取中间件信息
> feat(Middleware): 支持基于属性和方法的中间件

- src/support/App.php
自定义进程、插件进程增加enable属性，默认为true。enable=true的时候该进程为可用状态，可以启动，false的时候禁止启动。修改该字段需要restart重启项目
> 进程增加enable

- src/support/App.php
自定义进程增加enable参数,之前已经有人提过PR了
https://github.com/walkor/webman-framework/pull/108
我把我提交的去掉了
抱歉 提PR前没有同步fork
> support\helpers.php里的worker_start方法里面已经判断了enable,这里不需要了.

- src/support/Translation.php
> feat(i18n): Allow custom loader

- src/App.php
定义路由时设置额外参数：
```php
Route::any('/testclass', [app\controller\IndexController::class, 'test'])->setParams(['tpl_id' => 1]);
```
> 支持定义路由时附加参数
